---
apiVersion: v1
kind: Service
metadata:
  name: fe-srv-td
  labels:
    type: fe-srv-td
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"50051":{"name": "fe-srv-td"}}}'
spec:
  type: ClusterIP 
  ports:
  - name: fe
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: fe
