apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be-container
        image: salrashid123/grpc_backend
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /_ah/health
            port: 8081
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /_ah/health
            scheme: HTTPS
            port: 8081           
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 8081
          protocol: TCP                  
        command: ["./grpc_server"]
        args: ["--grpcport", ":50051", "--httpport", ":8081"]