apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be
spec:
  replicas: 5
  selector:
    matchLabels:
      app: be  
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be-container
        image: salrashid123/grpc_only_backend
        imagePullPolicy: Always         
        ports:
        - containerPort: 50051
          protocol: TCP                 
        command: ["./grpc_server"]
        args: ["--grpcport", ":50051"]